version: '3.8'

services:
  mysql:
    image: mysql:8.0.21
    platform: linux/x86_64
    container_name: database_api
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=senhaDoDB
    
    restart: always